title: My Jekyll Site
description: My awesome Jekyll site
baseurl: ""  # leave empty if publishing at root
url: "https://username.github.io"
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
paginate: 5